apiVersion: v1
kind: Service
metadata:
  name: myapp-loadbalancer
spec:
  type: LoadBalancer
  externalIPs:
  - 10.0.2.15
  selector:
    app: myapp
  ports:
  - name: "80"
    port: 80
    targetPort: 80