apiVersion: v1
kind: Service
metadata:
  name: myapp-loadbalancer
spec:
  type: LoadBalancer
  externalIPs:
  - 127.0.0.1
  selector:
    app: myapp
  ports:
  - name: "80"
    port: 80
    targetPort: 80